name: Release Please

on:
  push:
    branches:
      - master

jobs:
  release-please:
    runs-on: ubuntu-latest
    outputs:
      release-created: ${{ steps.release.outputs.release_created }}
    steps:
      - id: token
        uses: tibdex/github-app-token@v2
        with:
          app_id: ${{ secrets.APP_ID }}
          private_key: ${{ secrets.APP_PRIVATE_KEY }}

      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ steps.token.outputs.token }}
          release-type: node

  release:
    needs: release-please
    if: ${{ needs.release-please.outputs.release-created }}
    permissions:
      contents: read
      packages: write
    uses: ./.github/workflows/release.yml
    secrets: inherit
